[package]
name = "iced_audio"
version = "0.4.0"
authors = ["Billy Messenger <https://github.com/BillyDM>"]
license = "MIT"
edition = "2018"
keywords = ["iced", "gui", "audio", "vst", "lv2"]
categories = ["gui", "visualization"]
description = "An extension to the Iced GUI library with useful widgets for audio applications"
homepage = "https://github.com/BillyDM/iced_audio"
documentation = "https://docs.rs/iced_audio"
repository = "https://github.com/BillyDM/iced_audio"
readme = "README.md"

[badges]
maintenance = { status = "actively-developed" }

[workspace]
members = [
    "examples/simple",
    "examples/inputs_tour",
    "examples/scope",    
]

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
iced = { git = "https://github.com/hecrj/iced", branch = "master", features=["canvas"] }

[dependencies]
iced_native = { git = "https://github.com/hecrj/iced", branch = "master" }
iced_graphics = { git = "https://github.com/hecrj/iced", branch = "master", features=["canvas"] }
